### ISSUE TITLE
Question: does this setup completely replaces the experia box?

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [basmeerman/unifi-usg-kpn#15]
Does this setup completely replaces the experia box?

**Comment by markimarc** [comment]
Yes!

**Comment by mike-echo-oscar-whiskey** [comment]
Grant, got it working!

However, I did have to re-establish the PPPOE session using the controller UI.
Plus, that what got configured via provisioning to config does not seem to be reflected in the controller UI.
Finally, the USG is sometimes at 100% utilization, mostly when watching something 4K.

Some things are not clear to me, from the documentation.

* What exact IP ranges cannot be chosen?
* Do I need to configure IGMP Snooping?

I have a UniFi switch as well.

How important are the settings mentioned in this pull request?
https://github.com/basmeerman/unifi-usg-kpn/pull/13

**Comment by markimarc** [comment]
Cool! Did you also get voip working?

I've get the internet and iptv working, but not the bridge to the experiabox. (So the experiabox is back online at this moment...) :(

You can choose every ip range you want. As long as it isn't a public ip range... :)
You need to enable IGMP snooping if your using iptv. Otherwise you're broadcasting the whole network with the iptv signal, and you don't want that.

As far from #13, i don't know if you need those settings. I'll take a look this weekend.

What do you mean with 'Plus, that what got configured via provisioning to config does not seem to be reflected in the controller UI.'?
After provisioning, it goed back to connected. Right?

**Comment by basmeerman** [comment]
Closed due to inactivity.
