### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by coolhva** [basmeerman/unifi-usg-kpn#18]
Hi Bas,

Your configuration is used by many people in The Netherlands although I think you can improve your config in multiple ways:

- use kpn / kpn as username and password (makes it more easy)
- enable IPv6 (please look at my config: https://github.com/coolhva/usg-kpn-ftth)
- use DHCP RFC with exit hooks (https://github.com/coolhva/usg-kpn-ftth)
- Adjust MTU to lower CPU load on USG and lower fragmentation
- Cleaner config

Thanks for helping the community and I hope you find my additions useful.

**Comment by basmeerman** [comment]
Hi Henk,

Thanks for the suggestions. I've to look into these. My current home setup is different from the one stated here. Since posting the config I have split the network into several VLANS (added IOT/IOT_ISOLATED) and inter-VLAN firewall rules and optimized IGMP and broadcasting. I have not used IPV6 until now. 

If there is more interest I'll contribute and update the whole configuration.

Kind regards,

Bas

**Comment by Eskeemo** [comment]
Well I for one would be interested in the updated config. Especially the VLAN-part. Currently I have everything running with a json-file I found somewhere else (free2wifi), but there are two things I really would love to be able to do:
- add support for phone
- use VLAN's throughout my entire network

I currently have my USG connected directly to the KPN fiber, with 2 UniFi switches placed behind the USG. I thought I could just place one of the switches in front of the USG, connect the USG to one port of the Switch and connect the Experiabox to another port of the Switch, in order to get my phone back working. But I'm obviously missing something cause that didn't work.

Also I would like to send VLAN 4 en 6 to the network-part where my KPN settopboxes are connected to, and only VLAN 6 to the part where I just need internet. But I think the current json just lets the USG combine the VLANS to one trunk. Or am I wrong again :-)?

Thanks for all the effort and sharing! It's really appreciated.

Cheers,
Emiel
